### ISSUE TITLE
Not Giving items on join.

### ISSUE THREAD

**Issue by Nymorph** [ricksouth/serilum-mc-mods#2127]
## **Information**
Minecraft version: 1.19.2
Modloader: Forge
Forge version: 43.2.14
Environment: Multiplayer

Mod name: StarterKit
Mod version: 5.4

## **Description**
Not giving items on new join.

## **Crash report**
Log: https://gist.github.com/Nymorph/98d71d55f01a9b51836a247f222467c0
Config: https://gist.github.com/Nymorph/d89a1dbda278975c375a29cb0b954abc

**Comment by ricksouth** [comment]
I've released an update for Collective and Starter Kit to attempt to fix this issue. Could you see if it's working? I've also added extra logging. If it's not working, please re-upload the logs. Appreciate the opening of the issue!

**Comment by Unleashed75** [comment]
I have the same problem but on the fabric side.
Minecraft version: 1.20.1
Modloader: fabric 0.15.3
First noticed with StarterKit 5.4 and Collective 7.28
Tested the updated Collective 7.30 and Starter Kit 5.5 but still not working.

I thought it was a Luckperms or Carpet mod blocking it sort of thing but I rolled back to StarterKit 5.2 and Collective 6.57, to when I knew it worked on another server and that was ok.

I would help with sharing my log but I'm not that smart

**Comment by ricksouth** [comment]
Does it work if you disable the spawn check in the config? Also make sure the firstjoin tag is removed from the player joining

**Comment by Unleashed75** [comment]
My config "starterkit.json5" does not have any spawn check info or options, so maybe this is part of the problem and I need to delete it to get a new one.
It only has 2 options, both set to true;
"addExistingItemsAfterKitSet"
"enableFTBIslandCreateCompatibility"

As for firstjoin tag, I've been deleting the playerdata file for the player I've been testing with. So by rights, they should have no data, or tags or anything, right?

I'm a bit busy right now but when finished, I can run a few tests and hopefully send logs or find the user error inside of myself

**Comment by Unleashed75** [comment]
Yep, user error for me.

Deleting the config file "starterkit.json5" gave me the extra config code "enablePlayerMustBeNearSpawnForKitCheck" and when set to true, didn't work but when set to false, worked as it should.
Maybe you could add something to detect if any config line is missing and have it update?

I guess the true Spawn on the world has been moved.
Anyway, sorry to waste your time and thank you too

**Comment by ricksouth** [comment]
No it should definitely still work if the spawn has been moved! It's considered a bug. I recently added that to debug the problem. Do you know how the spawn was moved? With the command, or a different mod?

**Comment by Unleashed75** [comment]
I've no idea, I would of guessed the normal OP command "/setworldspawn".
It's from the Hermitcraft world download season 9.
Remaking the world from the seed, puts spawn at 0, 0 and on Hermitcraft it's moved to around -1770, 1515.

**Comment by ricksouth** [comment]
Thank you for opening the issue and giving the mod a try! This has been fixed in version 6.0 of Starter Kit, alongside many new features! See the description for more details:

https://curseforge.com/minecraft/mc-mods/starter-kit
