### ISSUE TITLE
"preventEndermenFromGriefing" is not working in Passive Enderman Mod.

### ISSUE THREAD

**Issue by Jusey1** [ricksouth/serilum-mc-mods#993]
## **Information**
Minecraft version: 1.16.5
Modloader: Forge
Forge version: 36.2.20 
Environment: Singleplayer

Mod name: Passive Enderman
Mod version: 2.1

## **Description**
So, the "preventEndermenFromGriefing" config option isn't working as I am getting Enderman whom be picking up ze' blocks which is honestly the main purpose of using this mod.

**Comment by ricksouth** [comment]
This has been fixed in version 2.3, thanks for letting me know!

https://www.curseforge.com/minecraft/mc-mods/passive-endermen/files

**Comment by Jusey1** [comment]
Um....
![Untitled](https://user-images.githubusercontent.com/61861078/159860919-75fb5fc3-7b73-4754-bd93-74ad33fd48dd.png)
.

**Comment by HeroOfAlexandria** [comment]
This issue doesn't seem to be fixed. I have the same issue in 1.18.2 version 2.3.

**Comment by JuneGame** [comment]
This appears to still be happening in Version 2.3 (MC 1.16.5) despite the changelogs.

**Comment by MarkusBordihn** [comment]
I can confirm. This is still not working in 1.18.2, the Endermen still picking up blocks and placing them.

![image](https://user-images.githubusercontent.com/12183293/174489408-95951f0a-fdfa-4e74-9a50-5133398294b9.png)

Found no errors in the logs, so it's seems to be something within the implementation itself.

**Comment by LuciusV** [comment]
Still not working with Forge 40.1.54, Passive Endermen 2.3, Collective 4.28

**Comment by ricksouth** [comment]
I was indeed wrong before about it not being fixed, apologies. Also for it taking so long. I have just released version 3.0 which fixes the multiple things that was causing this. Thank you for the patience, letting me know and giving the mod a try. I appreciate it.

https://www.curseforge.com/minecraft/mc-mods/passive-endermen/files
